# Base image for the final PostgreSQL image
FROM postgres:16

# Set the PostgreSQL environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=Users

# Expose the PostgreSQL port
EXPOSE 5432