FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_HOST=mysql
ENV MYSQL_DATABASE=Notifications
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password
ENV MYSQL_ROOT_PASSWORD=rootpassword

EXPOSE 3306