apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
  namespace: project-s-namespace
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      automountServiceAccountToken: false
      containers:
        - name: gateway
          image: projectscontainerregistry.azurecr.io/apigateway:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: "1"
              memory: 1Gi
