apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: project-s-namespace
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mysql
          image: projectscontainerregistry.azurecr.io/project-s-mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: "1"
              memory: 1Gi
